services:
  db:
    image: postgres:15
    container_name: url_shortener_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: url_shortener_redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/url_shortener?sslmode=disable"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3000:3000"

volumes:
  postgres_data:
