services:
  db:
    image: postgres:15
    container_name: url_shortener_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: url_shortener_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
